/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UiKitImport } from './routes/ui-kit'
import { Route as IndexImport } from './routes/index'
import { Route as ProfileIndexImport } from './routes/profile/index'
import { Route as ProfileTodosIndexImport } from './routes/profile/todos/index'
import { Route as ProfileTodosRecentIndexImport } from './routes/profile/todos/recent/index'
import { Route as ProfileTodosCreateIndexImport } from './routes/profile/todos/create/index'

// Create/Update Routes

const UiKitRoute = UiKitImport.update({
  path: '/ui-kit',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProfileIndexRoute = ProfileIndexImport.update({
  path: '/profile/',
  getParentRoute: () => rootRoute,
} as any)

const ProfileTodosIndexRoute = ProfileTodosIndexImport.update({
  path: '/profile/todos/',
  getParentRoute: () => rootRoute,
} as any)

const ProfileTodosRecentIndexRoute = ProfileTodosRecentIndexImport.update({
  path: '/profile/todos/recent/',
  getParentRoute: () => rootRoute,
} as any)

const ProfileTodosCreateIndexRoute = ProfileTodosCreateIndexImport.update({
  path: '/profile/todos/create/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/ui-kit': {
      id: '/ui-kit'
      path: '/ui-kit'
      fullPath: '/ui-kit'
      preLoaderRoute: typeof UiKitImport
      parentRoute: typeof rootRoute
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexImport
      parentRoute: typeof rootRoute
    }
    '/profile/todos/': {
      id: '/profile/todos/'
      path: '/profile/todos'
      fullPath: '/profile/todos'
      preLoaderRoute: typeof ProfileTodosIndexImport
      parentRoute: typeof rootRoute
    }
    '/profile/todos/create/': {
      id: '/profile/todos/create/'
      path: '/profile/todos/create'
      fullPath: '/profile/todos/create'
      preLoaderRoute: typeof ProfileTodosCreateIndexImport
      parentRoute: typeof rootRoute
    }
    '/profile/todos/recent/': {
      id: '/profile/todos/recent/'
      path: '/profile/todos/recent'
      fullPath: '/profile/todos/recent'
      preLoaderRoute: typeof ProfileTodosRecentIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ui-kit': typeof UiKitRoute
  '/profile': typeof ProfileIndexRoute
  '/profile/todos': typeof ProfileTodosIndexRoute
  '/profile/todos/create': typeof ProfileTodosCreateIndexRoute
  '/profile/todos/recent': typeof ProfileTodosRecentIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ui-kit': typeof UiKitRoute
  '/profile': typeof ProfileIndexRoute
  '/profile/todos': typeof ProfileTodosIndexRoute
  '/profile/todos/create': typeof ProfileTodosCreateIndexRoute
  '/profile/todos/recent': typeof ProfileTodosRecentIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/ui-kit': typeof UiKitRoute
  '/profile/': typeof ProfileIndexRoute
  '/profile/todos/': typeof ProfileTodosIndexRoute
  '/profile/todos/create/': typeof ProfileTodosCreateIndexRoute
  '/profile/todos/recent/': typeof ProfileTodosRecentIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ui-kit'
    | '/profile'
    | '/profile/todos'
    | '/profile/todos/create'
    | '/profile/todos/recent'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ui-kit'
    | '/profile'
    | '/profile/todos'
    | '/profile/todos/create'
    | '/profile/todos/recent'
  id:
    | '__root__'
    | '/'
    | '/ui-kit'
    | '/profile/'
    | '/profile/todos/'
    | '/profile/todos/create/'
    | '/profile/todos/recent/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UiKitRoute: typeof UiKitRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  ProfileTodosIndexRoute: typeof ProfileTodosIndexRoute
  ProfileTodosCreateIndexRoute: typeof ProfileTodosCreateIndexRoute
  ProfileTodosRecentIndexRoute: typeof ProfileTodosRecentIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UiKitRoute: UiKitRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  ProfileTodosIndexRoute: ProfileTodosIndexRoute,
  ProfileTodosCreateIndexRoute: ProfileTodosCreateIndexRoute,
  ProfileTodosRecentIndexRoute: ProfileTodosRecentIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/ui-kit",
        "/profile/",
        "/profile/todos/",
        "/profile/todos/create/",
        "/profile/todos/recent/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/ui-kit": {
      "filePath": "ui-kit.tsx"
    },
    "/profile/": {
      "filePath": "profile/index.tsx"
    },
    "/profile/todos/": {
      "filePath": "profile/todos/index.tsx"
    },
    "/profile/todos/create/": {
      "filePath": "profile/todos/create/index.tsx"
    },
    "/profile/todos/recent/": {
      "filePath": "profile/todos/recent/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
